openapi: "3.0.0"
info:
  title: BFP Service Model
  version: 1.0.0
paths:
  /initiateAuth:
    post:
      summary: Initiate auth and get credentials
      operationId: initiateAuth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateRequest'
      responses:
        200:
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateResponse'
  /file:
    post:
      summary: Upload a file
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: application/octet-stream
      responses:
        200:
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFileResponse'
  /file/{id}:
    get:
      summary: Get a file
      operationId: getFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved file
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary
              encoding:
                file:
                  contentType: application/octet-stream

components:
  schemas:
    AuthenticateRequest:
      type: object
      required:
        - username
        - password
      additionalProperties: false
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
    AuthenticateResponse:
      type: object
      required:
        - accessToken
      additionalProperties: false
      properties:
        accessToken:
          type: string
    CreateFileResponse:
      type: object
      required:
        - id
      additionalProperties: false
      properties:
        id:
          type: string