openapi: "3.0.0"
info:
  title: BFP Service Model
  version: 1.0.0
paths:
  /initiateAuth:
    get:
      summary: Initiate auth and get credentials
      operationId: initiateAuth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateAuthRequest'
      responses:
        200:
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateAuthResponse'
        400:
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    InitiateAuthRequest:
      type: object
      required:
        - username
        - password
      additionalProperties: false
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
    InitiateAuthResponse:
      type: object
      required:
        - accessToken
      additionalProperties: false
      properties:
        accessToken:
          type: string