version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Building BFP
      - mvn install --no-transfer-progress
artifacts:
  files:
    - BFPService/target/*.jar
  name: BFPService.jar
  discard-paths: yes
